// AUTO-GENERATED by scripts/generate-provider-images.mjs. Do not edit by hand.
// Maps a slugified service-provider name to its image in /public/providers.
export const PROVIDER_IMAGES: Record<string, string> = {
  "alner": "/providers/Alner.webp",
  "cupable": "/providers/Cupable.webp",
  "infinitybox": "/providers/Infinity_Box.webp",
  "kkpkp": "/providers/KKPKP.webp",
  "recube": "/providers/ReCube.webp",
  "weuse": "/providers/WeUse.webp",
  "back2basics": "/providers/back2basics.webp",
  "bangkokmetropolitanauthority": "/providers/bangkok-metropolitan-authority.webp",
  "hepicircle": "/providers/hepi-circle.webp",
  "irefill": "/providers/irefill.webp",
  "kkpkpwastepickercollectiveofpune": "/providers/kkpkp-wastepicker-collective-of-pune.webp",
  "refillablesdongday": "/providers/refillables-dong-day.webp",
  "shenzhenkuaipininformationtechnologyco": "/providers/shenzhen-kuaipin-information-technology-co.webp",
  "unileversmartfill": "/providers/unilever-smartfill.webp",
};
