// AUTO-GENERATED by scripts/generate-provider-images.mjs. Do not edit by hand.
// Maps a slugified service-provider name to its image in /public/providers.
export const PROVIDER_IMAGES: Record<string, string> = {
  "alner": "/providers/Alner.webp",
  "bopinc": "/providers/BoPinc.webp",
  "cupable": "/providers/Cupable.webp",
  "infinitybox": "/providers/Infinity_Box.webp",
  "recube": "/providers/ReCube.webp",
  "weuse": "/providers/WeUse.webp",
  "shuangti": "/providers/shuangti.webp",
};
